name: CI Angular

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install
        working-directory: ./front

      - name: Build du projet
        run: npm run build -- --configuration production
        working-directory: ./front

      - name: Lancer les tests avec coverage
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: ./front

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./front/coverage

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build & tests backend
        run: mvn clean verify
        working-directory: ./back

      - name: Upload coverage backend
        uses: actions/upload-artifact@v4
        with:
          name: coverage-backend
          path: ./back/target/site/jacoco

      - name: Analyse SonarQube
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          extraProperties: |
            sonar.projectKey=bobapp
            sonar.host.url=http://SONARQUBE_SERVER_URL
            sonar.login=${{ secrets.SONAR_TOKEN }}
